GET http://localhost:3000/api/joblist

###
POST http://localhost:3000/api/survey
Content-Type: application/json

{
    "email": "jane098@nycstudents.net",
    "SchoolID": 211,
    "JobTitle": "Financial Analyst",
    "CreatorEmail": "john123@nycstudents.net"
}

###
POST http://localhost:3000/api/results
Content-Type: application/json

{
   "SchoolID": 211
}
